// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnlnzjrbghhpvbmrmgjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpubG56anJiZ2hocHZibXJtZ2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDI5MjcsImV4cCI6MjA1NTQ3ODkyN30.9h9jVwC3VvDk2_BFYB_OKzw2QV6_NLIWseDrajtffOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);